# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bosun < Formula
  desc "A fast, clean terminal UI for managing Docker containers"
  homepage "https://github.com/psychedelicdevx/bosun"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/psychedelicdevx/bosun/releases/download/v0.3.0/bosun_0.3.0_darwin_amd64.tar.gz"
      sha256 "179c22e8a91766db5222eca8d3b1db4954966334fbf8a9174a212ec825850dc7"

      define_method(:install) do
        bin.install "bosun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/psychedelicdevx/bosun/releases/download/v0.3.0/bosun_0.3.0_darwin_arm64.tar.gz"
      sha256 "2f62ee383948624cdf8b8109f7599f6d758c1ce31d2a0c35592a2e801785749e"

      define_method(:install) do
        bin.install "bosun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/psychedelicdevx/bosun/releases/download/v0.3.0/bosun_0.3.0_linux_amd64.tar.gz"
      sha256 "acd2020bd7b35b913ed7c5757c20ab971e59194d63f15f450b2ae3429add691b"
      define_method(:install) do
        bin.install "bosun"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/psychedelicdevx/bosun/releases/download/v0.3.0/bosun_0.3.0_linux_arm64.tar.gz"
      sha256 "fca0826dee2618558081b3166a26aa50fd6480c9b2d873782311d55c0bd96eb4"
      define_method(:install) do
        bin.install "bosun"
      end
    end
  end

  test do
    system "#{bin}/bosun", "--version"
  end
end
