# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bosun < Formula
  desc "A fast, clean terminal UI for managing Docker containers"
  homepage "https://github.com/psychedelicdevx/bosun"
  version "0.6.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/psychedelicdevx/bosun/releases/download/v0.6.1/bosun_0.6.1_darwin_amd64.tar.gz"
      sha256 "4ad5acb7c01293d354f4bd7e655d7dd7bbf6648497862b90b7221f540e4d5bad"

      define_method(:install) do
        bin.install "bosun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/psychedelicdevx/bosun/releases/download/v0.6.1/bosun_0.6.1_darwin_arm64.tar.gz"
      sha256 "ac086e5e50966afccac2895d28a5c2f6b60444d5187f64a81797b4fc6a8a8540"

      define_method(:install) do
        bin.install "bosun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/psychedelicdevx/bosun/releases/download/v0.6.1/bosun_0.6.1_linux_amd64.tar.gz"
      sha256 "a0eaef0b47a793d9c7d4460ef8966518e1e2139977975ba10d7be56cc4daf5c0"
      define_method(:install) do
        bin.install "bosun"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/psychedelicdevx/bosun/releases/download/v0.6.1/bosun_0.6.1_linux_arm64.tar.gz"
      sha256 "2ecbc62278a80b9e3590c4f21fd10125f96c8a6664732fac02aaeaae756e257e"
      define_method(:install) do
        bin.install "bosun"
      end
    end
  end

  test do
    system "#{bin}/bosun", "--version"
  end
end
