# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bosun < Formula
  desc "A fast, clean terminal UI for managing Docker containers"
  homepage "https://github.com/psychedelicdevx/bosun"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/psychedelicdevx/bosun/releases/download/v0.5.0/bosun_0.5.0_darwin_amd64.tar.gz"
      sha256 "9ffc0006b0b6afd19b2d51778156d48a8abb7e597e31816d067ecb35e0aca6a1"

      define_method(:install) do
        bin.install "bosun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/psychedelicdevx/bosun/releases/download/v0.5.0/bosun_0.5.0_darwin_arm64.tar.gz"
      sha256 "53e330d9849906d4732c87a39c2bd0069f6b17069c4601879384b73cdd3c7256"

      define_method(:install) do
        bin.install "bosun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/psychedelicdevx/bosun/releases/download/v0.5.0/bosun_0.5.0_linux_amd64.tar.gz"
      sha256 "58ac17d95be7bad872f25e0478282d63da056c91e269293d748712dc87e0fbf4"
      define_method(:install) do
        bin.install "bosun"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/psychedelicdevx/bosun/releases/download/v0.5.0/bosun_0.5.0_linux_arm64.tar.gz"
      sha256 "828f2974b985016d5021ac3c9469b303aea997ca1acebf42a5441b6a3be3644b"
      define_method(:install) do
        bin.install "bosun"
      end
    end
  end

  test do
    system "#{bin}/bosun", "--version"
  end
end
